source 'https://ruby.taobao.org'

gem 'sinatra'
gem 'data_mapper'
gem 'nestful'
gem 'dm-sqlite-adapter'
gem 'zip'
gem 'yajl-ruby'
gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"

# gem 'dm-postgres-adapter'
